-- films from apollo kinokava
INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Dune: Part Two', 'Denis Villeneuve', 'SCIFI;ADVENTURE', 12, 166);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Kung Fu Panda 4', 'Mike Mitchell, Stephanie Strine', 'ANIMATION;ACTION;ADVENTURE', 0, 94);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Elu ja armastus', 'Helen Takkin', 'DRAMA', 12, 118);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Land of Bad', 'William Eubank', 'ACTION;THRILLER', 12, 113);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Kass ja koer: põgenemine', 'Reem Kherici', 'COMEDY;ADVENTURE', 6, 87);

-- more films generated by GPT
INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('The Grand Budapest Hotel', 'Wes Anderson', 'COMEDY;DRAMA', 15, 99);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Inception', 'Christopher Nolan', 'ACTION;SCIFI', 12, 148);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('The Lion King', 'Roger Allers, Rob Minkoff', 'ANIMATION;ADVENTURE;DRAMA', 0, 88);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Pulp Fiction', 'Quentin Tarantino', 'CRIME;DRAMA', 18, 154);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('The Shawshank Redemption', 'Frank Darabont', 'DRAMA', 15, 142);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('The Godfather', 'Francis Ford Coppola', 'CRIME;DRAMA', 18, 175);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Fight Club', 'David Fincher', 'DRAMA', 18, 139);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Forrest Gump', 'Robert Zemeckis', 'DRAMA;ROMANCE', 12, 142);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('The Matrix', 'Lana Wachowski, Lilly Wachowski', 'ACTION;SCIFI', 15, 136);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Interstellar', 'Christopher Nolan', 'ADVENTURE;DRAMA;SCIFI', 12, 169);

-- 5 estonian films from GPT
INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Tõde ja õigus', 'Tanel Toom', 'DRAMA', 12, 165);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Klass', 'Ilmar Raag', 'DRAMA', 15, 97);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('1944', 'Elmo Nüganen', 'DRAMA;WAR', 12, 100);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('November', 'Rainer Sarnet', 'DRAMA;FANTASY', 15, 115);

INSERT INTO Film (title, directors, genres, age_limit, duration)
VALUES ('Sangarid', 'Jaak Kilmi', 'COMEDY;DRAMA', 12, 90);

